[package]
name = "fib_web"
version = "0.1.0"
authors = ["Stephen Sherratt <stephen@sherra.tt>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
log = "0.4"
fib = { path = "../fib" }
prototty_web = { path = "../../../web" }
wasm-bindgen = "0.2"
wasm-logger = "0.2"
