[package]
name = "drag_ansi_terminal"
version = "0.1.0"
authors = ["Stephen Sherratt <stephen@sherra.tt>"]
edition = "2018"

[dependencies]
chargrid_ansi_terminal = { path = "../../../ansi-terminal" }
drag_app = { path = "../app" }
