[package]
name = "rip_native"
version = "0.1.0"
authors = ["Stephen Sherratt <stephen@sherra.tt>"]
edition = "2018"

[features]
force_dedicated_audio_thread = ["general_audio_native/force_dedicated_audio_thread"]

[dependencies]
log = "0.4"
simon = "0.4"
serde_json = "1.0"
rip_prototty = { path = "../prototty" }
general_storage_file = "0.1"
general_audio_native = "0.1"
