[package]
name = "tetris_wasm"
version = "0.1.0"
authors = ["Stephen Sherratt <sfsherratt@gmail.com>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
tetris = { path = "../tetris" }
tetris_prototty = { path = "../prototty" }
prototty = { path = "../../../prototty", version = "0.11.3" }
prototty_wasm = { path = "../../../wasm", version = "0.11.3" }
rand = "0.4"
