[package]
name = "roguelike_prototty"
version = "0.1.0"
authors = ["Stephen Sherratt <stephen@sherra.tt>"]
edition = "2018"

[dependencies]
prototty = { path = "../../../prototty", features = ["serialize"] }
prototty_storage = { path = "../../../storage", features = ["bincode"] }
prototty_audio = { path = "../../../audio" }
game = { path = "../game" }
serde = { version = "1.0", features = ["serde_derive"] }
hashbrown = { version = "0.6", features = ["serde"] }
rand = "0.7"
rand_isaac = { version = "0.2", features = ["serde1"] }
line_2d = "0.4"
direction = { version = "0.17", features = ["serialize", "rand"] }
