[package]
name = "tetris_prototty"
version = "0.1.0"
authors = ["Stephen Sherratt <sfsherratt@gmail.com>"]

[dependencies]
tetris = { path = "../tetris" }
prototty = { path = "../../../prototty", version = "0.15.0" }
prototty_common = { path = "../../../common", version = "0.15.0" }
rand = "0.4"
