[package]
name = "rip_prototty"
version = "0.1.0"
authors = ["Stephen Sherratt <stephen@sherra.tt>"]
edition = "2018"

[features]
wasm = ["rand/wasm-bindgen"]

[dependencies]
log = "0.4"
prototty = { path = "../../../prototty", features = ["serialize"] }
game = { path = "../game" }
serde = { version = "1.0", features = ["serde_derive"] }
rand = "0.7"
rand_isaac = { version = "0.2", features = ["serde1"] }
line_2d = "0.4"
direction = { version = "0.17", features = ["serialize", "rand"] }
maplit = "1.0"
general_storage = { version = "0.1", features = ["bincode", "json"] }
general_audio = "0.1"
