[package]
name = "prototty_file_storage"
description = "Implementation of prototty::Storage backed by files."
version = "0.14.0"
authors = ["Stephen Sherratt <sfsherratt@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/stevebob/prototty.git"
repository = "https://github.com/stevebob/prototty.git"
documentation = "https://docs.rs/prototty_file_storage"

[dependencies]
prototty = { path = "../prototty", version = "0.14.0" }
serde = "1.0"
bincode = "0.9"
