[package]
name = "prototty"
description = "Utilities for easily and efficiently rendering to a terminal."
version = "0.11.2"
authors = ["Stephen Sherratt <sfsherratt@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/stevebob/prototty.git"
repository = "https://github.com/stevebob/prototty.git"
documentation = "https://docs.rs/prototty"

[dependencies]
serde = "1.0"
serde_derive = "1.0"
