[package]
name = "chargrid_render"
description = "Traits for defining a renderer and a view"
version = "0.1.0"
authors = ["Stephen Sherratt <stephen@sherra.tt>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/stevebob/chargrid.git"
repository = "https://github.com/stevebob/chargrid.git"
documentation = "https://docs.rs/chargrid_render"
edition = "2018"

[features]
serialize = ["serde", "grid_2d/serialize", "rgb24/serialize"]

[dependencies]
serde = { version = "1.0", features = ["serde_derive"], optional = true }
coord_2d = "0.2"
grid_2d = "0.14"
rgb24 = "0.2"
