[package]
name = "fib"
version = "0.1.0"
authors = ["Stephen Sherratt <stephen@sherra.tt>"]
edition = "2018"

[dependencies]
prototty_storage = { path = "../../../storage", features = ["yaml"] }
serde = { version = "1.0", features = ["serde_derive"] }
