[package]
name = "prototty_common"
description = "Definition of common ui elements and views for use with prototty."
version = "0.10.0"
authors = ["Stephen Sherratt <sfsherratt@gmail.com>"]
license = "MIT"
homepage = "https://github.com/stevebob/prototty.git"
repository = "https://github.com/stevebob/prototty.git"
documentation = "https://docs.rs/prototty_common"

[dependencies]
prototty = { path = "..", version = "0.10.0" }
serde = "1.0"
serde_derive = "1.0"
