[package]
name = "rational"
version = "0.1.0"
authors = ["Stephen Sherratt <stephen@sherra.tt>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["serde_derive"] }
rand = "0.7"
