[package]
name = "colour_grid_ansi_terminal"
version = "0.1.0"
authors = ["Stephen Sherratt <stephen@sherra.tt>"]
edition = "2018"

[dependencies]
chargrid_ansi_terminal = { path = "../../../ansi-terminal" }
colour_grid_app = { path = "../app" }
simon = "0.4"
