[package]
name = "soundboard_web"
version = "0.1.0"
authors = ["Stephen Sherratt <stephen@sherra.tt>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
chargrid_web = { path = "../../../web", features = ["gamepad"] }
soundboard_app = { path = "../app" }
wasm-bindgen = "0.2"
console_error_panic_hook = "0.1"
wasm-logger = "0.2"
log = "0.4"
general_audio_web = "0.1"
