[package]
name = "soundboard_app"
version = "0.1.0"
authors = ["Stephen Sherratt <stephen@sherra.tt>"]
edition = "2018"

[dependencies]
chargrid = { path = "../../../chargrid", features = ["gamepad"] }
general_audio = "0.1"
