[package]
name = "unix_title"
version = "0.1.0"
authors = ["Stephen Sherratt <sfsherratt@gmail.com>"]

[dependencies]
prototty = { path = "../../../prototty", version = "0.15.0" }
prototty_unix = { path = "../../../unix", version = "0.15.0" }
prototty_title = { path = "../prototty" }
