[package]
name = "chargrid_text"
description = "chargrid text rendering"
version = "0.1.0"
authors = ["Stephen Sherratt <stephen@sherra.tt>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/stevebob/chargrid.git"
repository = "https://github.com/stevebob/chargrid.git"
documentation = "https://docs.rs/chargrid_text"
edition = "2018"

[features]
serialize = ["serde", "chargrid_render/serialize"]

[dependencies]
chargrid_render = { path = "../render", version = "0.1" }
serde = { version = "1.0", features = ["serde_derive"], optional = true }

[dev-dependencies]
chargrid_test_grid = { path = "../test-grid", version = "0.1" }
