[package]
name = "game"
version = "0.1.0"
authors = ["Stephen Sherratt <stephen@sherra.tt>"]
edition = "2018"

[dependencies]
grid_2d = { version = "0.13", features = ["serialize"] }
direction = { version = "0.17", features = ["serialize"] }
serde = { version = "1.0", features = ["serde_derive"] }
rand = "0.7"
rand_isaac = { version = "0.2", features = ["serde1"] }
line_2d = { version = "0.4", features = ["serialize"] }
rgb24 = { version = "0.2", features = ["serialize"] }
ecs = { path = "../ecs" }
vector = { path = "../vector" }
shadowcast = { version = "0.6", features = ["serialize"] }
